# Generated by Django 5.0.7 on 2024-07-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя магазина')),
                ('open', models.BooleanField(choices=[(True, 'Открыт'), (False, 'Закрыт')], default=False, verbose_name='Статус магазина')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Готовиться'), ('delivery', 'Доставка'), ('finished', 'Завершен')], default='preparing', max_length=20, verbose_name='Статус заказа')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='Магазин')),
            ],
        ),
    ]
