# Generated by Django 5.0.7 on 2024-07-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='ID заказа в учетной системе')),
                ('order_amount', models.IntegerField(default=0, verbose_name='Сумма заказа в учетной системе')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='Магазин')),
            ],
        ),
    ]
