# Generated by Django 5.0.7 on 2024-07-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_recordedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='ID заказа в учетной системе'),
        ),
    ]
